export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCES"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS"
export const NEW_USER_SUCCESS = "NEW_USER_SUCCESS"